language: r
use_devtools: true
before_install:
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
addons:
  apt:
    update: true
    packages:
      - libxml2-dev
      - libcurl4-openssl-dev
      - nodejs
before_script:
  - cd ui
  - npm install
  - npm run build
  - rm -r ../inst/ui && mkdir ../inst/ui
  - cp -r build ../inst/ui/
  - cd ..
script:
- R CMD build .
- R CMD check *tar.gz
- Rscript -e "devtools::test()"
